sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-005
env:
  global:
    -
      # LTD_AWS_ID
      secure: JIeIOt4KB5FNBavjIYzMb75eCE7Pa1bZTu6UPHZeJQpcqqYKcUMiNmO9yMaLszf5O26yzdaYgUev+t4FA8CwoktpLOq97KdBWD4pLAuUpGF1fcvt8U6lW67KirMbyyaiTp1lbQqdLQWQpbLGz9lKTZCsnAbTgqr8zsAQUWtePucPs7OfGB0HmmeAGkgA2WXgEf1So7FDwr0R1TqAOXzejVZThSIoKX1g47wLX4gqmMH5NzXO9t4LoU369FXud2G+Y85srcS9xSVMuheyBEyqIS/s1JOCM7572fk8KyIqNLf+rNq9OnYkSfLQN5LqQzRSbbkmwbwY7NIT8FEzW0oD3OB8uHee2fnRoQrCh7nPArz7ALONl45vBuZK7cKP0B5/MgMqAs8sjjNs0/wRjeRl2o4p6PyRIZXAI3XPFC9LocdkxeT83lGhsifprHoMvZH4gBaHScxChP8+RozcoXPTX1Y1uUPQsvvRg/0tq+2/6Q4WGG+1F4SbxnPB9eu0DpsH14YTK05AD3tWSsbmAxRX2YXlT72mJdqkt+22rBuJgFmMy0vrHrOfqmtBgIwtnoU8gMswJ9dRaCL5wWuD0cGIbPqZYzSnVmuTGvp8ukupA24K14xrDeZSy4mxWF8rS3r/waUf8pNeqT1JCAojEcJ0dbnpaUkZj20vqde7UA+HANE=
    -
      # LTD_AWS_SECRET
      secure: I2BvXiysRbUgT3W1Hi6cpu1ZSr2BdggToWWWjmY03yjaFWaJt5Rl61a616Y/u2Mk4E/xTRbDJcokJDAOBAmokaQrsHN+oVONujslaYqc4XgVRImtumGa73ZfcKDL3x+DxI3Wg6HX6s8U8hbwwlofOJYBvNmoTAuwZxLm7jy3+WTW4vkVQEl+SK61diRIUMbaY8tKB68G8GUmTNC3QGshSqb7LCRIwtbU5poIkj7/olnh5ZLP+lODjCfsXp6IGmSqacVHEGv2JCeTSj4DEQvBzrTtNbQVWdrbwW+wbI5+GG88qPBP6sTvH9YhjS4YeU3iTLFl287oMPIyQSoCYZxu336vzMDRf6/0v/JPKpZq0iwRtCjdfVyinIl2urYwk/0Vqozs3Ti/x6pY0aXtI6OEoNJJ8TtLqieXFQ0kfh/nSUeyOHrEjrVASq/1bK2gpgmLoRZrweHnnoWVsbsvSU83dzOCdDWgZmuoI1cCjrYZsfuKcJXw2ZG5lRVcXBC3jO1Mz5suwSh9nuUvtOW7V5KADRXA2fUMfblzOjyZPHIO81cMSfSMG7QwdGdP5C8t8Qy0WE2JBlyAxwjKV9pBoYlj2TG6RUcfp/ZVkHOMZaMCYKk/HpbAEAe3J12JD8Xz3K1aFqUSsgrOWXVp868QfrntPP5/J4lz7ztNT1fnE4j0ojM=
    -
      # LTD_USERNAME
      secure: LwKBM3NLny7ncgSYNcmfDy9p1WRDLnFHtckxo3rk2h5W3J7KNznaSj0GeR4rZjVnLFBVkyI8yOhgix7+4/71f7lS066Otx0/RJA4lnwzWXz/RT+6U8PJt40tEUzUWGVovkG1QNpOputQfmwaPnF6Asn5vWmATwoL6ZX6WcWI+UlXHuD5tRrUHxZQHsWD6qR5afTmhE4re1nUK2HS8c1DYXrtMNdLL+U2Ikow9l3CZt97lg6jVn0T5f2FH/pacVoqOpTDIDnXeeN/9XjBiArWNO1pzjZyADFrAVYw8FmgX4dMG2ZGiSSSpAQ4LEVJFfzm9Af9mu9fK/BV03wM1j9XCBUVDxnjidDzrRJ7bSB9rzfaYfu45AKGgvj/ZbjaX3aUOMj/urkp9aQpy7NBBfpVrUVpD+g2SEQbEwDeIuPOQmBAqmta8mK1VjolT2skB30+0mnK3pXCPVUNqMJFtcO8Y89+YEVp2btFS2cc3OcUk+5MXQHyn9hKtpFbgFIscWlsJAe44vc6N/8tx4Ri/Ez9hKzINpZJTlEYgrxtOOamVwKfZaViSzwuMQ/pWviEkM/K4TjGPncDCT0f1do7E5eFUQONRwD3cHGpWG+hv71LFWpmmJbFvDj9kr+mZYvy4f1gTjyAvbY0Jt/Y5cBkJ+kkvnyjtc3U7LenC1dUhp0J/Q0=
    -
      # LTD_PASSWORD
      secure: XkpNMPenGfoyPO4vc5AdiNFg3xUhVXvPgoneJCCuHWrQmpaKm1Jj00KYqrnFryro85QHttQfL8cz+7OippbmHbtbouW1Izd6V33Bf895Ab471d3EU2mNAbnMM5Km7kmWtOVTX1nD0p1LchcS6FJAvNfCxfeQNyolLkBAQCoCx/WwKjB5ZP1Kg2sapNwmnWny3utHiM+2ZpjL5LK22mKCShiCmiyE4V4/iKH2hItLCg38jNd/ImPkBh35GqhIZZBC6K25Lf4XqXUmkTv0XVAX6UmvSjt0vUqvBy2lFBfGaMTRgdBGiQmhuBIMYtbHIflfpRerCSuwbiO++ogakhtjnyzvEYO9nuIN8HWpjuTJVhKNfjvYRI/et6/lTP9SEzYL+RIyBOJ22mliLPTMGqnTD1pEmAv9PJBk0Dl9xDcLUtKgKuyBunASj7CCJfg5BFKkpqbKcM8jieAo/Aeb+mHdvEdKj4DeIaIqXDT9HB3V4TfAvNUveDLvc5LNhaLH6jQ70mxEvOImmBqnQ0vn4Hf6LHwtL6KTVtFguczbFzY4QokixqplvAGpdDH6xwV+Vx6SBcn+HSe5HZDd8X/Sj8/vThWbPcCCuAyC6jlQqK47e2rhU0aLy7JIrDlTUcBoEWrsqngZYTXf4OorrTRMktiNmGE4bEXqV/BfupNcwYJOoQo=
